# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/Nexys4DDR_Master.xdc

# Block Designs: /afs/athena.mit.edu/user/c/h/cherna/Documents/Nexys4FFTDemo-master/src/bd/fft_mag/fft_mag.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_mag || ORIG_REF_NAME==fft_mag}]

# IP: /afs/athena.mit.edu/user/c/h/cherna/Documents/Nexys4FFTDemo-master/src/bd/fft_mag/ip/fft_mag_axis_register_slice_2_0/fft_mag_axis_register_slice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_mag_axis_register_slice_2_0 || ORIG_REF_NAME==fft_mag_axis_register_slice_2_0}]

# IP: /afs/athena.mit.edu/user/c/h/cherna/Documents/Nexys4FFTDemo-master/src/bd/fft_mag/ip/fft_mag_c_addsub_0_0/fft_mag_c_addsub_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_mag_c_addsub_0_0 || ORIG_REF_NAME==fft_mag_c_addsub_0_0}]

# IP: /afs/athena.mit.edu/user/c/h/cherna/Documents/Nexys4FFTDemo-master/src/bd/fft_mag/ip/fft_mag_cordic_0_0/fft_mag_cordic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_mag_cordic_0_0 || ORIG_REF_NAME==fft_mag_cordic_0_0}]

# IP: /afs/athena.mit.edu/user/c/h/cherna/Documents/Nexys4FFTDemo-master/src/bd/fft_mag/ip/fft_mag_mult_gen_0_0/fft_mag_mult_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_mag_mult_gen_0_0 || ORIG_REF_NAME==fft_mag_mult_gen_0_0}]

# IP: /afs/athena.mit.edu/user/c/h/cherna/Documents/Nexys4FFTDemo-master/src/bd/fft_mag/ip/fft_mag_mult_gen_1_0/fft_mag_mult_gen_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_mag_mult_gen_1_0 || ORIG_REF_NAME==fft_mag_mult_gen_1_0}]

# IP: /afs/athena.mit.edu/user/c/h/cherna/Documents/Nexys4FFTDemo-master/src/bd/fft_mag/ip/fft_mag_xfft_0_0/fft_mag_xfft_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_mag_xfft_0_0 || ORIG_REF_NAME==fft_mag_xfft_0_0}]

# IP: /afs/athena.mit.edu/user/c/h/cherna/Documents/Nexys4FFTDemo-master/src/bd/fft_mag/ip/fft_mag_xlconstant_0_0/fft_mag_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_mag_xlconstant_0_0 || ORIG_REF_NAME==fft_mag_xlconstant_0_0}]

# IP: /afs/athena.mit.edu/user/c/h/cherna/Documents/Nexys4FFTDemo-master/src/bd/fft_mag/ip/fft_mag_xlconstant_1_0/fft_mag_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_mag_xlconstant_1_0 || ORIG_REF_NAME==fft_mag_xlconstant_1_0}]

# IP: /afs/athena.mit.edu/user/c/h/cherna/Documents/Nexys4FFTDemo-master/src/bd/fft_mag/ip/fft_mag_xlconstant_2_0/fft_mag_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_mag_xlconstant_2_0 || ORIG_REF_NAME==fft_mag_xlconstant_2_0}]

# IP: /afs/athena.mit.edu/user/c/h/cherna/Documents/Nexys4FFTDemo-master/src/bd/fft_mag/ip/fft_mag_xlslice_0_0/fft_mag_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_mag_xlslice_0_0 || ORIG_REF_NAME==fft_mag_xlslice_0_0}]

# IP: /afs/athena.mit.edu/user/c/h/cherna/Documents/Nexys4FFTDemo-master/src/bd/fft_mag/ip/fft_mag_xlslice_1_0/fft_mag_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_mag_xlslice_1_0 || ORIG_REF_NAME==fft_mag_xlslice_1_0}]

# IP: /afs/athena.mit.edu/user/c/h/cherna/Documents/Nexys4FFTDemo-master/src/bd/fft_mag/ip/fft_mag_xlconcat_0_0/fft_mag_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_mag_xlconcat_0_0 || ORIG_REF_NAME==fft_mag_xlconcat_0_0}]

# XDC: /afs/athena.mit.edu/user/c/h/cherna/Documents/Nexys4FFTDemo-master/src/bd/fft_mag/fft_mag_ooc.xdc
